---

openshift_cluster_content:
- object: PersistentVolume
  content:
  - name: "pv_5Gi_ReadWriteOnce"
    file: "templates/pv/pv_5Gi_ReadWriteOnce"
    action: create
  - name: "pv_10Gi_ReadWriteMany"
    file: "templates/pv/pv_10Gi_ReadWriteMany"
    action: create
- object: namespace
  content:
  - name: cicd
    template: "templates/projects/projects.template"
    params_from_vars: "{{ cicd }}"
    action: create
    no_log: false
  - name: cicd-dev
    template: "templates/projects/projects.template"
    params_from_vars: "{{ cicd_dev }}"
    action: create
  - name: cicd-test
    template: "templates/projects/projects.template"
    params_from_vars: "{{ cicd_test }}"
    action: create
  - name: cicd-prod
    template: "templates/projects/projects.template"
    params_from_vars: "{{ cicd_prod }}"
    action: create
- object: Template
  content:
  - name: jenkins
    namespace: cicd
    template: "templates/apps/jenkins.yml"
    params_from_vars:
      ENABLE_OAUTH: false
    action: create
- object: Policy
  content:
  - name: jenkins cicd-dev access
    namespace: cicd-dev
    template: "templates/policy/rbac_template.yml"
    params_from_vars: "{{ cicd_jenkins_edit }}"
    action: create
  - name: jenkins cicd-test access
    namespace: cicd-test
    template: "templates/policy/rbac_template.yml"
    params_from_vars: "{{ cicd_jenkins_edit }}"
    action: create
  - name: jenkins cicd-prod access
    namespace: cicd-prod
    template: "templates/policy/rbac_template.yml"
    params_from_vars: "{{ cicd_jenkins_edit }}"
    action: create  
  - name: cicd-test image-puller 
    namespace: cicd-dev
    template: "templates/policy/rbac_template.yml"
    params_from_vars: "{{ cicd_jenkins_edit }}"
    action: create
  - name: cicd-prod image-puller 
    namespace: cicd-dev
    template: "templates/policy/rbac_template.yml"
    params_from_vars: "{{ cicd_jenkins_edit }}"
    action: create
- object: NetworkPolicy
  content:
  - name: ingress-to-jenkins-cicd-from-outside
    namespace: cicd
    file: 'templates/networkpolicy/allow_jenkins.yml'
    action: create
- object: Deployments
  content:
  - name: Deploy openshift tasks to cicd-dev
    namespace: cicd-dev
    template: 'https://raw.githubusercontent.com/paddy667/openshift-tasks/master/app-template.yaml'
    params_from_vars: "{{ openshift_tasks_params }}"
  - name: Deploy openshift tasks to cicd-dev
    namespace: cicd-test
    template: 'https://raw.githubusercontent.com/paddy667/openshift-tasks/master/app-template.yaml'
    params_from_vars: "{{ openshift_tasks_params }}"
  - name: Deploy openshift tasks to cicd-dev
    namespace: cicd-prod
    template: 'https://raw.githubusercontent.com/paddy667/openshift-tasks/master/app-template.yaml'
    params_from_vars: "{{ openshift_tasks_params }}"

#- object: HorizontalPodAutoscaler
#  content:
#    - name: tasks-hpa
#      file: "hpa/hpa_template.yml"
#
#      action: create

